import './globals.css'
import type {Metadata} from 'next'
import {ThemeProvider} from '../components/MaterialTailwind'
import React from "react";
import localFont from "next/font/local";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head>
            <meta name="mobile-web-app-capable" content="yes"/>
            <link
                rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
                integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
                crossOrigin="anonymous"
                referrerPolicy="no-referrer"
            />
            <link rel="shortcut icon" href="/icons/favicon.ico" />
            <link rel="icon" href="/icons/favicon.ico" />
            <link rel="apple-touch-icon" href="/icons/favicon.ico" />
            <title>ui</title>
        </head>
        <ThemeProvider>
            <body>
            <div className="min-h-screen min-w-screen"
                 style={{
                    paddingTop: 0,
                    paddingLeft: 0,
                    backgroundColor: '#000000'
                 }}>
                    
                <div className="transition-all"
                    style={{
                        width: '100vw',
                        height: '100vh',
                    }}>

                    <div className="flex flex-col" style={{width: '100vw', height: '100vh'}}>   
                        {children}
                    </div>
                </div>
        
            </div>
            </body>
        </ThemeProvider>
        </html>
    )
}
